import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import baseURL from "@/services/baseUrl";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const getCategories = async () => {
  const res = await fetch(`${baseURL}/categories`, {
    cache: "force-cache",
  });
  const data = await res.json();
  return data;
};

export default async function RootLayout({ children }) {

  const categories = await getCategories();
  // console.log(categories);

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body suppressHydrationWarning className="min-h-full flex flex-col">
        <Navbar categories={categories}/>
        {children}
      </body>
    </html>
  );
}
